# Generated by Django 4.1.7 on 2023-02-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentid', models.IntegerField(blank=True, null=True)),
                ('responsetype', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('time', models.TimeField()),
                ('enddate', models.DateField()),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
