# Generated by Django 4.1.7 on 2023-03-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0002_remove_incident_enddate_incident_exposuretime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='smokepresent',
        ),
        migrations.AlterField(
            model_name='incident',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
