# Generated by Django 4.1.7 on 2023-03-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0003_remove_incident_smokepresent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='time',
        ),
    ]
